# Generated by Django 4.2.17 on 2025-01-17 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='skip_recaptcha',
            field=models.BooleanField(default=False, help_text='Check this box to bypass reCAPTCHA validation in admin.', verbose_name='Skip reCAPTCHA in admin'),
        ),
    ]
