services:
  web:
    build: .
    command: >
      sh -c "echo $DB_HOST &&
             until pg_isready -h $DB_HOST -p 5432; do sleep 1; done &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    env_file:
      - .env
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - default

  db:
    image: postgres:latest
    env_file:
      - .env
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 15s
      timeout: 5s
      retries: 10
    networks:
      - default

networks:
  default:
    driver: bridge
